import Head from 'next/head';
import { useRouter } from 'next/router';
import { Loading, Progress } from 'src/components/elements';
import { SearchBar } from 'src/components/elements/SearchBar';
import { ModalPaper } from 'src/components/layouts';
import DataGrid from 'src/components/layouts/DataGrid';
import { useModal } from 'src/hooks';

import styles from './Home.module.css';

const Home = () => {
    const TestModal = useModal('test', { id: 2 });
    const TextModal = useModal('text');
    const router = useRouter();
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <SearchBar />
                <Progress />

                <button
                    onClick={() => {
                        TextModal.openModal();
                    }}
                >
                    text 모달창 열기
                </button>
                <button
                    onClick={() => {
                        TestModal.openModal();
                    }}
                >
                    Test 모달창{' '}
                </button>
                <Loading state={true} />
                <DataGrid>
                    <DataGrid.Title>test Word</DataGrid.Title>
                    <DataGrid.SubTitle>SubTitle</DataGrid.SubTitle>
                </DataGrid>
            </div>

            <TestModal.Portal>
                {router.query.modal === 'text' && (
                    <ModalPaper>
                        <button
                            onClick={() => {
                                TextModal.closeModal();
                            }}
                        >
                            닫기
                        </button>
                        모달창
                    </ModalPaper>
                )}
                {router.query.modal === 'test' && (
                    <ModalPaper>
                        <button
                            onClick={() => {
                                TestModal.closeModal();
                            }}
                        >
                            닫기
                        </button>
                        id : {router.query?.id}
                    </ModalPaper>
                )}
            </TestModal.Portal>
        </>
    );
};

export default Home;
